### ISSUE TITLE
proxmox - cc2531 cant connect any zigbee sensors 

### ISSUE THREAD

**Issue by onlinegill** [zigpy/zigpy-cc#69]
Hi, I am not able to connect ZigBee sensors when I am using cc2531 with proxmox VM. I am able to pass through dongle but cant connect any sensors however if i use same dongle on RPI3 or virtual box I am  able to pair them.

**Comment by Hedda** [comment]
Troubleshooting 101 - I think that you have really ruled out that the issue is not with zigpy-cc but with your proxmox VM setup.

That really does not sound like an issue with the zigpy-cc library but with your VM not properly passing through the dongle.

If it is Home Assistant Core you are using on any Linux then suggest post in the Home Assistant Community Forum for support

https://community.home-assistant.io

If it is Home Assistant operating-system (Hass.io) then maybe post an issue to their repo first:

https://github.com/home-assistant/operating-system/issues
